"""Collect environment transitions on the CPU while the GPU trains, at the same time.

Phase 0 of this project measured that MuJoCo physics on the CPU workers and PyTorch updates
on the Metal GPU barely interfere: run concurrently, the CPU retains 91.5% of its solo
throughput and the GPU 100.3%. That measurement has been sitting unused, because every
trainer here runs collection and learning in strict alternation:

    [ 49 ms physics ] [ 295 ms gradients ] [ 49 ms physics ] [ 295 ms gradients ] ...

Overlapping them costs `max(physics, gradients)` instead of the sum. PPO CANNOT do this: it
needs data generated by the policy currently being optimised, so it must stop the world at
every update. Off-policy learning has no such requirement, which makes this the one genuine
architectural advantage of TD3 here, and the reason it is worth building rather than just
tuning batch sizes.

Two rules keep it correct, and both matter:

* **The learner owns the replay buffer, exclusively.** The actor thread never touches it. It
  hands finished chunks over a queue and the learner inserts them between updates. Sharing
  the buffer across threads would let a sampled batch mix the observation of one transition
  with the action of another, which is not a race you would ever see in a loss curve.
* **The actor holds a SNAPSHOT of the policy**, refreshed on request. Reading the live
  network while the learner writes it gives torn weights: half an optimiser step. Common
  practice in distributed RL (Ape-X actors pull weights periodically) and it costs one copy
  of a small network.

The replay ratio stays the control knob. The learner asks for a specific number of new
environment steps before each round of updates, so whichever side is slower sets the pace
and the ratio is honoured exactly rather than drifting with load.
"""

from __future__ import annotations

import queue
import threading
import time
from dataclasses import dataclass

import numpy as np
import torch


@dataclass
class Chunk:
    """One vectorised step, ready for the buffer. Kept on CPU until the learner takes it."""

    obs: np.ndarray
    actions: np.ndarray
    rewards: np.ndarray
    next_obs: np.ndarray
    keep_going: np.ndarray
    #: Finished episodes in this step, for the training-side curves the dashboard charts.
    episode_returns: np.ndarray
    episode_lengths: np.ndarray
    reward_terms: np.ndarray


class AsyncCollector:
    """Runs the environment in a background thread and queues transitions for the learner."""

    def __init__(self, env, actor: torch.nn.Module, device: torch.device,
                 explore_std: torch.Tensor, *, queue_size: int = 4) -> None:
        self.env = env
        self.device = device
        self.explore_std = explore_std
        # The actor's own copy. Never the learner's live network.
        self.policy = self._clone(actor)
        self._weight_lock = threading.Lock()
        self._queue: queue.Queue[Chunk] = queue.Queue(maxsize=queue_size)
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self.steps_collected = 0
        #: Wall seconds the actor spent blocked because the learner was behind. If this is
        #: large the GPU is the bottleneck and the replay ratio is too high for this machine.
        self.blocked_seconds = 0.0

    @staticmethod
    def _clone(actor: torch.nn.Module) -> torch.nn.Module:
        import copy

        clone = copy.deepcopy(actor)
        clone.eval()
        for p in clone.parameters():
            p.requires_grad_(False)
        return clone

    def sync_weights(self, actor: torch.nn.Module) -> None:
        """Publish the learner's current policy to the actor. Cheap; call every round."""
        with self._weight_lock:
            with torch.no_grad():
                for dst, src in zip(self.policy.parameters(), actor.parameters()):
                    dst.copy_(src)

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, name="collector", daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=10.0)

    @torch.no_grad()
    def _run(self) -> None:
        """Step the environment forever, queueing each vectorised step.

        MuJoCo steps and MPS kernels both release the GIL, which is what allows this thread
        to make real progress while the learner runs. If either did not, this would silently
        degrade to the sequential loop it replaces, so the trainer logs actor and learner
        throughput separately and the comparison is the check.
        """
        obs = self.env.reset()
        while not self._stop.is_set():
            obs_t = torch.as_tensor(obs, dtype=torch.float32, device=self.device)
            with self._weight_lock:
                action = self.policy(obs_t)
            action = (action + torch.randn_like(action) * self.explore_std).clamp(-1.0, 1.0)
            action_np = action.cpu().numpy()
            result = self.env.step(action_np)

            # Same two subtleties as the synchronous trainer, and they are just as load
            # bearing here: next_obs must be the FINAL observation where an episode ended,
            # and only a genuine termination stops the bootstrap. A time-limit truncation
            # has a real future worth learning from.
            next_obs = result.obs.copy()
            done = result.done
            if done.any():
                next_obs[done] = result.final_obs[done]
            finished = np.flatnonzero(done)

            chunk = Chunk(
                obs=obs.copy(),
                actions=action_np,
                rewards=result.reward.copy(),
                next_obs=next_obs,
                keep_going=(~result.terminated).astype(np.float32),
                episode_returns=result.episode_return[finished].copy(),
                episode_lengths=result.episode_length[finished].copy(),
                reward_terms=result.reward_terms.mean(axis=0),
            )
            obs = result.obs

            start = time.perf_counter()
            while not self._stop.is_set():
                try:
                    self._queue.put(chunk, timeout=0.1)
                    break
                except queue.Full:
                    continue
            self.blocked_seconds += time.perf_counter() - start
            self.steps_collected += self.env.num_envs

    def drain(self, min_steps: int, timeout: float = 30.0) -> list[Chunk]:
        """Block until at least `min_steps` environment steps are available, then take all.

        This is where the replay ratio is enforced. The learner names how much fresh data it
        wants and takes EXACTLY that much, never the whole backlog.

        Draining the backlog is what the first version did, and it silently destroyed the
        thing it was built to measure. The actor ran eight times ahead of the learner, every
        drain returned eight chunks at once, and the configured replay ratio of 16 became an
        actual 1.9. Throughput appeared to improve 4.5x and none of it was concurrency; it
        was the ratio quietly collapsing. Leftovers stay queued, and a short queue applies
        backpressure so the actor cannot sprint ahead in the first place.
        """
        chunks: list[Chunk] = []
        collected = 0
        deadline = time.perf_counter() + timeout
        while collected < min_steps:
            remaining = deadline - time.perf_counter()
            if remaining <= 0:
                break
            try:
                chunk = self._queue.get(timeout=min(remaining, 1.0))
            except queue.Empty:
                continue
            chunks.append(chunk)
            collected += chunk.obs.shape[0]
        return chunks
