"""Get-up reference clips, generated by RISING. Feasible by construction.

E47, replacing a reference that could not be executed. The previous version (kept as
`generate_getup_reference_reversed_DEPRECATED.py`) recorded a gentle scripted DESCENT
(stand -> squat -> seated -> supine) and reversed time, on the argument that a reversed
feasible trajectory is feasible. It is not, and the measurement is brutal: commanding the
reversed film's own joint angles as servo targets, from its own first pose, the pelvis went
0.094 -> 0.111 while the "reference" went 0.095 -> 0.879, falling 0.18 m behind by 23% of
the way through. Descending is gravity-assisted; rising fights gravity with the same
actuators. Four runs learned to chase a film no controller can perform, and did the only
thing available: rode it to 99% of its phase while staying 15 cm low.

Here the clip is produced by actually STANDING UP under the same servos that will have to
reproduce it, and kept only if the body genuinely arrives standing and stays. What survives
is feasible by construction, and the executability test now runs before the file is
written rather than after four hours of training.

    python scripts/generate_getup_reference.py    # writes data/fallen/getup_refs_v2.npz
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import mujoco
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from humanoid_rl.envs.model_prep import prepare  # noqa: E402

N_CLIPS = 8
#: A clip is accepted only if the pelvis ends at least this high, after a settle.
STAND_Z = 0.82
#: ...and it must not have been a jump: the root stays under this speed throughout.
SPEED_CAP = 1.4


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bank", type=Path, default=REPO_ROOT / "data/fallen/bank_v3.npz")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "data/fallen/getup_refs_v2.npz")
    ap.add_argument("--seed", type=int, default=5)
    ap.add_argument("--attempts", type=int, default=4000)
    args = ap.parse_args()

    prepared = prepare(REPO_ROOT / "humanoid_rl/models/humanoid_scene.xml",
                       action_scale_mode="full_range")
    model = prepared.model
    data = mujoco.MjData(model)
    qadr = prepared.actuator_qpos_adr
    lo, hi = model.actuator_ctrlrange[:, 0], model.actuator_ctrlrange[:, 1]
    names = list(prepared.joint_names)
    rng = np.random.default_rng(args.seed)

    bank = np.load(args.bank, allow_pickle=False)
    lab = bank["label"]
    lying = np.flatnonzero((lab == "supine") | (lab == "prone")
                           | (lab == "side_left") | (lab == "side_right"))
    nominal = prepared.default_joint_pos.copy()

    def waypoint(kind: str, r: np.random.Generator) -> np.ndarray:
        """Servo targets for one stage of the rise, randomised within a family."""
        j = nominal.copy()

        def setj(sub: str, value: float, side: str = "") -> None:
            for i, n in enumerate(names):
                if sub in n and (not side or n.startswith(side)):
                    j[i] = value

        if kind == "tuck":            # knees in, feet planted, propped on the arms
            setj("knee", r.uniform(2.0, 2.7))
            setj("hip_y", -r.uniform(1.6, 2.3))
            setj("abdomen_y", r.uniform(0.2, 0.7))
            setj("shoulder_y", -r.uniform(0.8, 1.6))
            setj("elbow", -r.uniform(0.5, 1.4))
        elif kind == "squat":         # weight over the feet, torso pitched forward
            setj("knee", r.uniform(1.7, 2.3))
            setj("hip_y", -r.uniform(1.4, 2.0))
            setj("abdomen_y", r.uniform(0.4, 0.9))
            setj("ankle_y", r.uniform(-0.6, 0.2))
            setj("shoulder_y", -r.uniform(0.3, 1.0))
        elif kind == "half":          # knees extending, torso lifting
            setj("knee", r.uniform(0.7, 1.4))
            setj("hip_y", -r.uniform(0.5, 1.1))
            setj("abdomen_y", r.uniform(0.1, 0.4))
            setj("ankle_y", r.uniform(-0.3, 0.1))
        return np.clip(j, lo, hi)

    clips_q, clips_v, bounds = [], [], [0]
    kept = 0
    tried = 0
    best_seen = 0.0
    while kept < N_CLIPS and tried < args.attempts:
        tried += 1
        data.qpos[:] = bank["qpos"][lying[rng.integers(0, lying.size)]]
        data.qvel[:] = 0.0
        mujoco.mj_forward(model, data)
        stages = [("tuck", rng.uniform(0.9, 1.6)),
                  ("squat", rng.uniform(0.8, 1.5)),
                  ("half", rng.uniform(0.5, 1.1)),
                  ("stand", rng.uniform(0.6, 1.2))]
        traj = []
        current = data.qpos[qadr].copy()
        ok = True
        for kind, seconds in stages:
            target = waypoint(kind, rng)
            steps = int(seconds / model.opt.timestep)
            for t in range(steps):
                a = (t + 1) / steps
                data.ctrl[:] = np.clip(current + a * (target - current), lo, hi)
                mujoco.mj_step(model, data)
                if t % 4 == 0:
                    if float(np.linalg.norm(data.qvel[0:3])) > SPEED_CAP:
                        ok = False
                        break
                    traj.append((data.qpos.copy(), data.qvel.copy()))
            if not ok:
                break
            current = target
        if not ok or not traj:
            continue
        # Settle at the stand: the clip must END standing and STAY, not pass through.
        for t in range(int(1.0 / model.opt.timestep)):
            data.ctrl[:] = np.clip(nominal, lo, hi)
            mujoco.mj_step(model, data)
            if t % 4 == 0:
                traj.append((data.qpos.copy(), data.qvel.copy()))
        z_end = float(data.qpos[2])
        best_seen = max(best_seen, z_end)
        if z_end < STAND_Z:
            continue
        clips_q.append(np.stack([a for a, _ in traj]))
        clips_v.append(np.stack([b for _, b in traj]))
        bounds.append(bounds[-1] + len(clips_q[-1]))
        kept += 1

    if kept == 0:
        raise RuntimeError(
            f"no clip stood up in {tried} attempts (best pelvis {best_seen:.3f} against "
            f"{STAND_Z} required). These waypoint families cannot rise under these servos. "
            f"That is a finding about the body, not a reason to lower the bar.")

    np.savez_compressed(
        args.out, qpos=np.concatenate(clips_q), qvel=np.concatenate(clips_v),
        bounds=np.array(bounds, dtype=np.int64),
        nq=model.nq, nv=model.nv, dt=model.opt.timestep * 4,
        model_sha1=bank["model_sha1"], generator_version=2,
    )
    lens = np.diff(bounds)
    z0 = [float(c[0][2]) for c in clips_q]
    z1 = [float(c[-1][2]) for c in clips_q]
    print(f"{kept} clips kept of {tried} attempts -> {args.out}")
    print(f"  length {lens.min()}-{lens.max()} steps "
          f"({lens.min()*0.008:.1f}-{lens.max()*0.008:.1f} s)")
    print(f"  start pelvis {min(z0):.3f}-{max(z0):.3f}  ->  end {min(z1):.3f}-{max(z1):.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
